# Generated by Django 4.2.4 on 2023-09-05 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('especialidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('dni', models.IntegerField(unique=True, verbose_name='DNI')),
                ('sexo', models.CharField(choices=[('', 'Seleccione una opcion'), ('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=10, verbose_name='Sexo')),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion')),
                ('telefono', models.CharField(max_length=50, verbose_name='Telefono')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Email')),
                ('estado_civil', models.CharField(choices=[('', 'Seleccione una opcion'), ('Soltero/a', 'Soltero/a'), ('Casado/a', 'Casado/a'), ('Viudo/a', 'Viudo/a'), ('Separado/a', 'Separado/a')], max_length=50, verbose_name='Estado Civil')),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('activo', models.BooleanField(default=True, verbose_name='Estado')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='especialidades.especialidad')),
            ],
            options={
                'verbose_name': 'medico',
                'verbose_name_plural': 'medicos',
                'db_table': 'medicos',
                'ordering': ['apellido', 'nombre'],
            },
        ),
    ]
