# Generated by Django 4.2.4 on 2023-09-07 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='hora',
            field=models.CharField(choices=[('10:00 a 11:00', '10:00 a 11:00'), ('11:00 a 12:00', '11:00 a 12:00'), ('12:00 a 13:00', '12:00 a 13:00'), ('13:00 a 14:00', '13:00 a 14:00'), ('14:00 a 15:00', '14:00 a 15:00'), ('15:00 a 16:00', '15:00 a 16:00'), ('16:00 a 17:00', '16:00 a 17:00'), ('17:00 a 18:00', '17:00 a 18:00'), ('18:00 a 19:00', '18:00 a 19:00')], max_length=50, verbose_name='Hora'),
        ),
    ]
