# Generated by Django 4.2.4 on 2023-09-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_alter_turno_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='hora',
            field=models.CharField(choices=[('10:00 a 10:30', '10:00 a 10:30'), ('10:30 a 11:00', '10:30 a 11:00'), ('11:00 a 11:30', '11:00 a 11:30'), ('11:30 a 12:00', '11:30 a 12:00'), ('12:00 a 12:30', '12:00 a 12:30'), ('12:30 a 13:00', '12:30 a 13:00'), ('13:00 a 13:30', '13:00 a 13:30'), ('13:30 a 14:00', '13:30 a 14:00'), ('14:00 a 14:30', '14:00 a 14:30'), ('14:30 a 15:00', '14:30 a 15:00'), ('15:00 a 15:30', '15:00 a 15:30'), ('15:30 a 16:00', '15:30 a 16:00'), ('16:00 a 16:30', '16:00 a 16:30'), ('16:30 a 17:00', '16:30 a 17:00'), ('17:00 a 17:30', '17:00 a 17:30'), ('17:30 a 18:00', '17:30 a 18:00'), ('18:00 a 18:30', '18:00 a 18:30'), ('18:30 a 19:00', '18:30 a 19:00')], max_length=50, verbose_name='Hora'),
        ),
    ]
